swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
tags:
  - name: "user"
    description: "About user page"
    externalDocs:
      description: "Find out more"
      url: "http://localhost:8080"
  - name: "tickets"
    description: "All tickets page"
    externalDocs:
      description: "Find out more about our store"
      url: "http://localhost:8080"
schemes:
  - http
paths:
  /user/users:
    get:
      tags:
        - "user"
      summary: Returns a list of users.
      description: For admin, get all users.
      operationId: "getUsers"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Returns a list of users"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
          description: "successful"
        "404":
          description: "Invalid status value"
    post:
      tags:
        - "user"
      summary: Create different user type.
      description: Create new user.
      operationId: "addUser"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Create different user type."
          required: true
          schema:
            $ref: "#/definitions/createUser"
      responses:
        "200":
          schema:
            items:
              $ref: "#/definitions/createUser"
          description: "successful"
        "400":
          description: "Invalid status value"
    put:
      tags:
        - "user"
      summary: Update different type user(admin).
      description: Update different type user.
      operationId: "updatedUser"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Update different type user"
          required: true
          schema:
            $ref: "#/definitions/createUser"
      responses:
        "200":
          schema:
            $ref: "#/definitions/createUser"
          description: "successful"
        "400":
          description: "Invalid status value"
    delete:
      tags:
        - "user"
      summary: Delete user.
      description: Delete user.
      operationId: "DeleteUser"
      produces:
        - application/json
      responses:
        "200":
          description: "successful"
        "400":
          description: "Invalid status value"

  /user/{user_type}/{user_account}:
    get:
      tags:
        - "user"
      summary: Returns a list of users.
      description: For admin, get all users.
      operationId: "getUsers"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Get user information"
          required: true
          schema:
            items:
              $ref: "#/definitions/UserUpdate"
      responses:
        "200":
          schema:
            items:
              $ref: "#/definitions/UserUpdate"
          description: "successful"
        "400":
          description: "Invalid status value"
    put:
      tags:
        - "user"
      summary: Update user information.
      description: Update user information.
      operationId: "updateUsers"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Update user information"
          required: true
          schema:
            items:
              $ref: "#/definitions/UserUpdate"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserUpdate"
          description: "successful"
        "400":
          description: "Invalid status value"

  /user/{user_type}/{user_account}/tickets:
    get:
      tags:
        - "tickets"
      summary: Returns a list of tickets.
      description: For different user type, get all tickets.
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Create different type ticket"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Ticket"
      responses:
        200:
          schema:
            items:
              $ref: "#/definitions/Ticket"
          description: Successful
    post:
      tags:
        - "tickets"
      summary: Create different type ticket(admin).
      description: For different user, create ticket.
      operationId: "addUsers"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Create different type ticket"
          required: true
          schema:
            items:
              $ref: "#/definitions/Ticket"
      responses:
        "200":
          schema:
            items:
              $ref: "#/definitions/Ticket"
          description: "successful"
        "400":
          description: "Invalid status value"

  /user/{user_type}/{user_account}/tickets/{ticket_type}:
    get:
      tags:
        - "tickets"
      summary: Returns ticket content.
      description: For different ticket type, get ticket content.
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Get different type ticket"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Ticket"
      responses:
        200:
          description: OK
        400:
          description: "Invalid status value"
    post:
      tags:
        - "tickets"
      summary: Create different type ticket(admin).
      description: For different user, create ticket.
      operationId: "addUsers"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Create different type ticket"
          required: true
          schema:
            items:
              $ref: "#/definitions/Ticket"
      responses:
        "200":
          schema:
            items:
              $ref: "#/definitions/Ticket"
          description: "successful"
        "400":
          description: "Invalid status value"
    delete:
      tags:
        - "tickets"
      summary: Create different type ticket(admin).
      description: For different user, create ticket.
      operationId: "addUsers"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Delete tickets"
          required: true
          schema:
            items:
              $ref: "#/definitions/Ticket"
      responses:
        200:
          description: "successful"
        400:
          description: "Invalid status value"

  /user/{user_type}/{user_account}/tickets/{ticket_type}/{id}:
    get:
      tags:
        - "tickets"
      summary: Returns the specified ticket id content.
      description: For different ticket id, get ticket content.
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Get different id ticket"
          required: true
          schema:
            items:
              $ref: "#/definitions/Ticket"
      responses:
        200:
          description: OK
        400:
          description: "Invalid status value"
    put:
      tags:
        - "tickets"
      summary: Update the specified ticket id content.
      description: Update the specified ticket id content.
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Get different id ticket"
          required: true
          schema:
            items:
              $ref: "#/definitions/Ticket"
      responses:
        200:
          description: OK
        400:
          description: "Invalid status value"
    delete:
      tags:
        - "tickets"
      summary: Delete ticket.
      description: Delete ticket.
      operationId: "deleteTicket"
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Delete different id ticket"
          required: true
          schema:
            items:
              $ref: "#/definitions/Ticket"
      responses:
        200:
          description: "successful"
        400:
          description: "Invalid status value"

definitions:
  Ticket:
    type: "object"
    required:
      - "summary"
      - "description"
    properties:
      status:
        type: "integer"
        example: 200
      message:
        type: "object"
        properties:
          id:
            $ref: "#/definitions/MongoObjId"
          ticket_type:
            description: "ticket type"
            enum:
              - "Bug"
              - "Feature"
              - "Test Case"
          summary:
            type: "string"
            example: "bug"
          description:
            type: "string"
            example: "bug description"
          ticket_status:
            type: "string"
            description: "bug status"
            enum:
              - "New"
              - "Start"
              - "Close"
              - "Resolve"
              - "Verify"
          priority:
            type: "string"
            description: "bug priority"
            enum:
              - "High"
              - "Medium"
              - "Low"
          severity:
            type: "string"
            description: "bug severity"
            enum:
              - "Critical"
              - "Major"
              - "Moderate"
              - "Minor"
              - "Cosmetic"
          create_date:
            $ref: "#/definitions/Epoch"
            description: "bug create time(epoch)"
          expected_date:
            $ref: "#/definitions/Epoch"
            description: "bug expected resolve time(epoch)"
          resolve_date:
            $ref: "#/definitions/Epoch"
            description: "bug resolved time(epoch)"
          reporter:
            type: "string"
            example: "Code Leader"
            description: "query user db"
          assignee:
            type: "string"
            example: "Jeremy"
            description: "query user db"
  User:
    type: "object"
    required:
      - "account"
    properties:
      status:
        type: "integer"
        example: 200
      message:
        type: "object"
        properties:
          id:
            $ref: "#/definitions/MongoObjId"
          account:
            type: "string"
            example: "Jeremy"
          user_type:
            type: "string"
            enum:
              - "Admin"
              - "RD"
              - "QA"
              - "PM"
  UserUpdate:
    type: "object"
    required:
      - "account"
    properties:
      status:
        type: "integer"
        example: 200
      message:
        type: "object"
        properties:
          password:
            type: "string"
            example: "Jeremy"

  createUser:
    type: "object"
    required:
      - "account"
      - "password"
    properties:
      status:
        type: "integer"
        example: 200
      message:
        type: "object"
        properties:
          id:
            $ref: "#/definitions/MongoObjId"
          account:
            type: "string"
            example: "Jeremy"
          password:
            type: "string"
            example: "pass"
          user_type:
            type: "string"
            enum:
              - "Admin"
              - "RD"
              - "QA"
              - "PM"
          authority:
            type: integer
            enum:
              - 0
              - 1
              - 2
              - 3
  MongoObjId:
    type: string
    format: ObjectId
    pattern: '^(?=[a-f\d]{24}$)(\d+[a-f]|[a-f]+\d)'
  Epoch:
    type: integer
    format: int64
    description: 'Epoch time in milliseconds.'
